routes/web.php
<?php

use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('home');
});
// Route::get('/user', 'UserController@index');
// Route::get('/user/create', 'UserController@create'); 
Route::resource('user', 'UserController');  
Route::resource('Estacionamientos', 'EstacionamientosController')->middleware('auth');
// Auth::routes();

// Route::get('/home', 'HomeController@index')->name('home');

Auth::routes(['register'=>false,'reset'=>false]);

Route::get('/home', 'HomeController@index')->name('home');

app/Estacionamientos.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Estacionamientos extends Model
{
    //
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/EstacionamientosController.php
<?php

namespace App\Http\Controllers;

use App\Estacionamientos;
use Illuminate\Http\Request;

class EstacionamientosController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $datos['estacionamientos']=Estacionamientos::paginate(20);

        return view('estacionamientos.index', $datos);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('estacionamientos.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        
        $campos=[
            'Nombre'=>'required|string|max:100',
            'Direccion'=>'required|string|max:191',
            'Latitud'=>'required|numeric|max:90',
            'Longitud'=>'required|numeric|max:90',
            'Espacios'=>'required|numeric|max:1000'
        ];
        $Mensaje=["required"=>'El :attribute es Requerido'];
        $this->validate($request,$campos,$Mensaje);

        $datosEstacionamiento=request()->except('_token');
        Estacionamientos::insert($datosEstacionamiento);
        return redirect('Estacionamientos')->with('Mensaje', 'Estacionamineto agregado con éxito');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Estacionamientos  $estacionamientos
     * @return \Illuminate\Http\Response
     */
    public function show(Estacionamientos $estacionamientos)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Estacionamientos  $estacionamientos
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $estacionamiento=Estacionamientos::findOrFail($id);

        return view('Estacionamientos.edit',compact('estacionamiento'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Estacionamientos  $estacionamientos
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $datosEstacionamiento=request()->except(['_token','_method']);
        Estacionamientos::where('id','=',$id)->update($datosEstacionamiento);
        
        return redirect('Estacionamientos')->with('Mensaje', 'Estacionamiento se ha actualizado');
        // $estacionamiento=Estacionamientos::findOrFail($id);
        // return view('Estacionamientos.edit',compact('estacionamiento'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Estacionamientos  $estacionamientos
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Estacionamientos::destroy($id);
        return redirect('Estacionamientos')->with('Mensaje', 'El estacionamiento se ha eliminado');
    }
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $datos['users']=User::paginate(20);

        return view('user.index', $datos);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('user.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $datosUser=request()->except('_token');

        $datosUser['password']=Hash::make($datosUser['password']);
        User::insert($datosUser);
        return redirect('user')->with('Mensaje', 'Usuario agregado con éxito');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\User  $users
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $datosUser=request()->except(['_token','_method']);
        User::where('id','=',$id)->update($datosUser);

        return redirect('user')->with('Mensaje', 'El usuario ha sido actualizado');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        User::destroy($id);
        return redirect('user')->with('Mensaje', 'El Usuario se ha eliminado con éxito');
    }
}

resources/views/estacionamientos/create.blade.php
@extends('layouts.app')

@section('content')

<div class="container">

    @if(count($errors)>0)
        <div class="alert alert-danger" role="alert">
            <ul>
                @foreach($errors->all() as $error)
                    <li>{{$error}}</li>
                @endforeach
            </ul>
        </div>
    @endif
    <form action="{{url('/Estacionamientos')}}" class="form-horizontal" method="POST">
    {{ csrf_field() }}

    @include('estacionamientos.form',['Modo'=>'crear'])


    </form>
</div>
@endsection

resources/views/estacionamientos/edit.blade.php
@extends('layouts.app')

@section('content')

<div class="container">

    @if(count($errors)>0)
        <div class="alert alert-danger" role="alert">
            <ul>
                @foreach($errors->all() as $error)
                    <li>{{$error}}</li>
                @endforeach
            </ul>
        </div>
    @endif
    <form action="{{ url('/Estacionamientos/'.$estacionamiento->id) }}" method="post" enctype="multipart/form-data">
        {{csrf_field()}}
        {{method_field('PATCH')}}

        @include('estacionamientos.form',['Modo'=>'editar'])
    </form>
</div>
@endsection

resources/views/estacionamientos/form.blade.php
<div class="form-group">
    <label for="Nombre" class="control-label">{{'Nombre'}}</label>
    <input type="text" class="form-control" name="Nombre" id="Nombre" 
    value="{{isset($estacionamiento->nombre)?$estacionamiento->nombre:''}}">
</div>

<div class="form-group">
    <label for="Direccion" class="control-label">{{'Dirección'}}</label>
    <input type="text" class="form-control" name="Direccion" id="Direccion" 
    value="{{isset($estacionamiento->direccion)?$estacionamiento->direccion:''}}">
</div>
<div class="form-group">
    <label for="Latitud" class="control-label">{{'Latitud'}}</label>
    <input type="number" class="form-control" step="any" name="Latitud" id="Latitud" 
    value="{{isset($estacionamiento->latitud)?$estacionamiento->latitud:''}}">
</div>
<div class="form-group">
    <label for="Longitud" class="control-label">{{'Longitud'}}</label>
    <input type="number" class="form-control" step="any" name="Longitud" id="Longitud" 
    value="{{isset($estacionamiento->longitud)?$estacionamiento->longitud:''}}">
</div>
<div class="form-group">
    <label for="N° Espacios" class="control-label">{{'Espacios'}}</label>
    <input type="number" class="form-control" name="Espacios" id="Espacios" 
    value="{{isset($estacionamiento->espacios)?$estacionamiento->espacios:''}}">
</div>

<input type="submit" class="btn btn-success" value="{{$Modo=='crear'?'Agregar':'Modificar'}}">

<a class="btn btn-primary" href="{{url('Estacionamientos')}}">Cancelar</a>

resources/views/estacionamientos/index.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
@if(Session::has('Mensaje'))
    <div class="alert alert-success" role="alert">
        {{Session::get('Mensaje')}}
    </div>
@endif
<a href="{{url('Estacionamientos/create')}}" class="btn btn-primary">Agregar</a>
<br/>
<br/>
<Table class="table table-light table-hover">
    <thead class="thead-light">
        <tr>
            <th>N°</th>
            <th>Nombre</th>
            <th>Dirección</th>
            <th>Acción</th>
        </tr>
    </thead>
    <tbody>
        @foreach($estacionamientos as $estacionamiento)
        <tr>
            <td>{{$loop->iteration}}</td>
            <td>{{$estacionamiento->nombre}}</td>
            <td>{{$estacionamiento->direccion}}</td>
            <td>
                <a class="btn btn-warning" href="{{url('/Estacionamientos/'.$estacionamiento->id.'/edit')}}">
                    Editar
                </a>
                <form method="post" action="{{ url('/Estacionamientos/'.$estacionamiento->id) }}" style="display:inline">
                {{csrf_field() }}
                {{ method_field('DELETE') }}
                <button class="btn btn-danger" type="submit" onclick="return confirm('¿Esta seguro?');">Borrar</button>
                </form>

            </td>
        </tr>
        @endforeach
    </tbody>

</Table>
{{$estacionamientos->links()}}
</div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
<center>
    <img src="{{asset('/images/logo.png')}}"  width="400" height="400" alt="">
    </center>
</div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>ParkOne</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                <img src="{{asset('/images/logo.png')}}"  width="30" height="30" alt="">ParkOne
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->

                    <ul class="navbar-nav mr-auto" >
                        <li class="nav-item">
                                <a class="nav-link" href="{{ route('Estacionamientos.index') }}">{{ __('Estacionamientos') }}</a>
                        </li>
                        <li class="nav-item">
                                <a class="nav-link" href="{{ route('user.index') }}">{{ __('Usuarios') }}</a>
                        </li>
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/user/create.blade.php
@extends('layouts.app')

@section('content')

<div class="container">

    @if(count($errors)>0)
        <div class="alert alert-danger" role="alert">
            <ul>
                @foreach($errors->all() as $error)
                    <li>{{$error}}</li>
                @endforeach
            </ul>
        </div>
    @endif
    <form action="{{url('/user')}}" class="form-horizontal" method="POST">
    {{ csrf_field() }}

    @include('user.form',['Modo'=>'crear'])


    </form>
</div>
@endsection

resources/views/user/edit.blade.php
@extends('layouts.app')

@section('content')

<div class="container">

    @if(count($errors)>0)
        <div class="alert alert-danger" role="alert">
            <ul>
                @foreach($errors->all() as $error)
                    <li>{{$error}}</li>
                @endforeach
            </ul>
        </div>
    @endif
    <form action="{{ url('/User/'.$user->id) }}" method="post" enctype="multipart/form-data">
        {{csrf_field()}}
        {{method_field('PATCH')}}

        @include('user.form',['Modo'=>'editar'])
    </form>
</div>
@endsection

resources/views/user/form.blade.php
<div class="form-group">
    <label for="rut" class="control-label">{{'RUT'}}</label>
    <input type="text" class="form-control" name="rut" id="rut" 
    value="{{isset($user->rut)?$user->rut:''}}">
</div>
<div class="form-group">
    <label for="name" class="control-label">{{'Nombre'}}</label>
    <input type="text" class="form-control" name="name" id="name" 
    value="{{isset($user->name)?$user->name:''}}">
</div>
<div class="form-group">
    <label for="email" class="control-label">{{'e-mail'}}</label>
    <input type="email" class="form-control" step="any" name="email" id="email" 
    value="{{isset($user->email)?$user->email:''}}">
</div>
<div class="form-group">
    <label for="rol" class="control-label">{{'Rol'}}</label>
        <select name="rol" class="form-control"> 
            <option value="1">Administrador</option>    
            <option value="0">Empleado</option>  
        </select>         
</div>
<div class="form-group">
    <label for="estado" class="control-label">{{'Estado'}}</label>
    <select name="estado" class="form-control">    
        <option value="1">Activo</option>    
        <option value="0">inactivo</option>   
    </select>   
</div>
<div class="form-group">
    <label for="estacionamientos_id" class="control-label" >{{'Estacionamiento'}}</label>
        <select name="estacionamientos_id" class="form-control" > 
            <option value="1">Aeromundo</option>    
            <option value="2">Aeromundo 2</option>  
        </select>         
</div>
<div class="form-group">
    <label for="password" class="control-label">{{'Contraseña'}}</label>
    <input type="password" class="form-control" name="password" id="password" 
    value="{{isset($user->password)?$user->password:''}}">
</div>

<input type="submit" class="btn btn-success" value="{{$Modo=='crear'?'Agregar':'Modificar'}}">

<a class="btn btn-primary" href="{{url('user')}}">Cancelar</a>

resources/views/user/index.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
@if(Session::has('Mensaje'))
    <div class="alert alert-success" role="alert">
        {{Session::get('Mensaje')}}
    </div>
@endif
<a href="{{url('user/create')}}" class="btn btn-primary">Agregar</a>
<br/>
<br/>
<Table class="table table-light table-hover">
    <thead class="thead-light">
        <tr>
            <th>N°</th>
            <th>RUT</th>
            <th>Nombre</th>
            <th>e-mail</th>
            <th>Rol</th>
            <th>Acción</th>
        </tr>
    </thead>
    <tbody>
        @foreach($users as $user)
        <tr>
            <td>{{$loop->iteration}}</td>
            <td>{{$user->rut}}</td>
            <td>{{$user->name}}</td>
            <td>{{$user->email}}</td>
            <td>Administrador</td>
            <td>
                <a class="btn btn-warning" href="{{url('/user/'.$user->id.'/edit')}}">
                    Editar
                </a>
                <form method="post" action="{{ url('/user/'.$user->id) }}" style="display:inline">
                {{csrf_field() }}
                {{ method_field('DELETE') }}
                <button class="btn btn-danger" type="submit" onclick="return confirm('¿Esta seguro?');">Borrar</button>
                </form>

            </td>
        </tr>
        @endforeach
    </tbody>

</Table>
{{$users->links()}}
</div>
@endsection